project:
  type: website
  title: "Michael Armah"

website:
  navbar:
    pinned: true
    search: true
    title: false
    left:
      - icon: house-door-fill
        text: " "
        file: index.qmd
      - text: "Teaching"
        file: teaching.qmd
#      - text: "Contact"
#        file: contact.qmd
      - text: "Resume"
        file: resume3.pdf
      - text: "CV"
        file: Academic_CV.pdf

format:
  html:
    theme:
      - pulse
      - styles.scss
    toc: true
    smooth-scroll: true
    anchor-sections: true



