project:
  type: website
  title: "Michael Armah"

website:
  navbar:
    pinned: true
    search: true
    title: false
    left:
      - icon: house-door-fill
        text: " "
        file: index.qmd
      - text: "Teaching"
        file: teaching.qmd
#      - text: "Contact"
#        file: contact.qmd
      - text: "Resume"
        file: resume3.pdf
      - text: "CV"
        file: Academic_CV.pdf
    right: 
#      - icon: mortarboard-fill
      - text: STEPP Center
        href: https://steppcenter.northwestern.edu/
        target: _blank
      - text: Team
        href: https://steppcenter.northwestern.edu/people/
        target: _blank
      - text: Department
        href: https://statistics.northwestern.edu/
        target: _blank



  page-footer:
    left: "[Michael Armah](https://github.com/MichaelArmah) &copy; <script>document.write(new Date().getFullYear())</script>"
    right:
      - icon: github
        href: https://github.com/MichaelArmah
        target: _blank

format:
  html:
    theme:
      - pulse
      - styles.scss
    toc: true
    smooth-scroll: true
    anchor-sections: true


